# Generated by Django 2.1.2 on 2018-10-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('question', models.TextField()),
                ('weight', models.DecimalField(decimal_places=1, default=1, max_digits=2, null=True)),
                ('min_legend', models.CharField(blank=True, help_text='Meaning of the answer with the lowest score.', max_length=155, null=True)),
                ('max_legend', models.CharField(blank=True, help_text='Meaning of the answer with the highest score.', max_length=155, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sections.Section')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
