# Generated by Django 2.1.2 on 2018-11-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
