# Generated by Django 2.0.6 on 2018-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, null=True),
        ),
    ]
