# Generated by Django 2.0.6 on 2018-06-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('answers', '0002_auto_20180618_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
            preserve_default=False,
        ),
    ]
