# Generated by Django 2.1.2 on 2018-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20181118_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='target_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
