# Generated by Django 2.0.6 on 2018-07-12 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ('modified', 'name')},
        ),
        migrations.AddField(
            model_name='assessment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
